#pragma once

enum class FloatOperatorType
{
	FLOAT_OPERATOr_TYPE_LESS,
	FLOAT_OPERATOR_TYPE_LESS_OR_EQUALS,
	FLOAT_OPERATOR_TYPE_EQUALS,
	FLOAT_OPERATOR_TYPE_GREATER_OR_EQUALS,
	FLOAT_OPERATOR_TYPE_GREATER,
	FLOAT_OPERATOR_TYPE_NOT_EQUALS
};