#pragma once

enum class GameObjectType
{
	OBJECT_TYPE_UNKNOWN,
	OBJECT_TYPE_UNIT,
	OBJECT_TYPE_DOODADS,
	OBJECT_TYPE_ANIMATED_DOODADS,
	OBJECT_TYPE_TREE,
	OBJECT_TYPE_ANIMATED_TREE,
	OBJECT_TYPE_ANIMATED_BANNER,
	OBJECT_TYPE_COLLISION_BOX,
	OBJECT_TYPE_SPECIAL_EFFECT,
	OBJECT_TYPE_REGION_POINT,
	OBJECT_TYPE_SHADOW,
	OBJECT_TYPE_AGENT,
	OBJECT_TYPE_INTERFACE,
	OBJECT_TYPE_PROJECTILE,
	OBJECT_TYPE_LINE_COLLISION_AGENT,
	OBJECT_TYPE_RECT_COLLISION_AGENT,
	OBJECT_TYPE_NPC,
	OBJECT_TYPE_REGION_AGENT,
	OBJECT_TYPE_RENDER_AGENT
};