#pragma once

enum class IntegerOperatorType
{
	INTEGER_OPERATOR_TYPE_LESS,
	INTEGER_OPERATOR_TYPE_LESS_OR_EQUALS,
	INTEGER_OPERATOR_TYPE_EQUALS,
	INTEGER_OPERATOR_TYPE_GREATER_OR_EQUALS,
	INTEGER_OPERATOR_TYPE_GREATER,
	INTEGER_OPERATOR_TYPE_NOT_EQUALS
};