#pragma once

enum ModelStance
{
	MODEL_STANCE_TOWNWALK = 0,
	MODEL_STANCE_TOWNNEUTRAL = 1,
	MODEL_STANCE_SPECIALCAST = 2,
	MODEL_STANCE_GETHIT = 3,
	MODEL_STANCE_KICK = 4,
	MODEL_STANCE_SPECIAL_1 = 5,
	MODEL_STANCE_WALK = 6,
	MODEL_STANCE_ATTACK_1 = 7,
	MODEL_STANCE_NEUTRAL = 8,
	MODEL_STANCE_ATTACK_2 = 9,
	MODEL_STANCE_RUN = 10,
	MODEL_STANCE_SPECIAL_3 = 11,
	MODEL_STANCE_SPECIAL_4 = 12,
	MODEL_STANCE_DEATH = 13,
	MODEL_STANCE_DEAD = 14
};