#pragma once

enum ModelStance
{
	MODEL_STANCE_ATTACK_1 = 0,
	MODEL_STANCE_ATTACK_2 = 1,
	MODEL_STANCE_GETHIT = 2,
	MODEL_STANCE_KICK = 3,
	MODEL_STANCE_NEUTRAL = 4,
	MODEL_STANCE_RUN = 5,
	MODEL_STANCE_SPECIALCAST = 6,
	MODEL_STANCE_SPECIAL_1 = 7,
	MODEL_STANCE_SPECIAL_2 = 8,
	MODEL_STANCE_SPECIAL_3 = 9,
	MODEL_STANCE_TOWNNEUTRAL = 10,
	MODEL_STANCE_TOWNWALK = 11,
	MODEL_STANCE_WALK = 12,
	MODEL_STANCE_DEATH = 13,
	MODEL_STANCE_DEAD = 14
};