#pragma once

enum class ObjectAnchorType
{
		OBJECT_ANCHOR_TYPE_TOP_LEFT,
		OBJECT_ANCHOR_TYPE_TOP,
		OBJECT_ANCHOR_TYPE_TOP_RIGHT,
		OBJECT_ANCHOR_TYPE_LEFT,
		OBJECT_ANCHOR_TYPE_CENTER,
		OBJECT_ANCHOR_TYPE_RIGHT,
		OBJECT_ANCHOR_TYPE_BOTTOM_LEFT,
		OBJECT_ANCHOR_TYPE_BOTTOM,
		OBJECT_ANCHOR_TYPE_BOTTOM_RIGHT,
		COUNT
};