#pragma once

enum ObjectAnchorType
{
		OBJECT_ANCHOR_TYPE_TOP_LEFT,
		OBJECT_ANCHOR_TYPE_TOP_CENTER,
		OBJECT_ANCHOR_TYPE_TOP_RIGHT,
		OBJECT_ANCHOR_TYPE_CENTER_CENTER,
		OBJECT_ANCHOR_TYPE_BOTTOM_BOTTOM,
		OBJECT_ANCHOR_TYPE_BOTTOM_CENTER,
		OBJECT_ANCHOR_TYPE_BOTTOM_RIGHT,
		OBJECT_ANCHOR_TYPE_RIGHT_CENTER,
		OBJECT_ANCHOR_TYPE_CENTER
};