#pragma once

enum class PlayerSlot
{
	PLAYER_SLOT_P1,
	PLAYER_SLOT_P2,
	PLAYER_SLOT_P3,
	PLAYER_SLOT_P4,
	PLAYER_SLOT_P5,
	PLAYER_SLOT_P6,
	PLAYER_SLOT_P7,
	PLAYER_SLOT_P8,
	PLAYER_SLOT_NEUTRAL,
	PLAYER_SLOT_NEUTRAL_ENEMY,
	PLAYER_SLOT_NEUTRAL_RESCUE,
	PLAYER_SLOT_NEUTRAL_SPECIAL,
	PLAYER_SLOT_S1,
	PLAYER_SLOT_S2,
	PLAYER_SLOT_S3,
	PLAYER_SLOT_S4,
	COUNT
};