--io.write(string.format("Hello from %s\n", _VERSION))
--StartServer(1234)
SetTilesMultiplier(135)
LoadTexture("../../content/Textures/models/barbarian/barbarian_run.png")
LoadTexture("../../content/Textures/models/barbarian/barbarian_townneutral.png")
LoadTexture("../../content/Textures/models/enemy/enemy_walk.png")
LoadTexture("../../content/Textures/models/enemy/enemy_townneutral.png")

--LoadTexture("../../content/Textures/models/Hero/buckler.png")
--LoadTexture("../../content/Textures/models/Hero/clothes.png")
--LoadTexture("../../content/Textures/models/Hero/dagger.png")
--LoadTexture("../../content/Textures/models/Hero/greatbow.png")
--LoadTexture("../../content/Textures/models/Hero/greatstaff.png")
--LoadTexture("../../content/Textures/models/Hero/greatsword.png")
--LoadTexture("../../content/Textures/models/Hero/leather_armor.png")
--LoadTexture("../../content/Textures/models/Hero/longbow.png")
--LoadTexture("../../content/Textures/models/Hero/longsword.png")
--LoadTexture("../../content/Textures/models/Hero/male_head1.png")
--LoadTexture("../../content/Textures/models/Hero/male_head2.png")
--LoadTexture("../../content/Textures/models/Hero/male_head3.png")
--LoadTexture("../../content/Textures/models/Hero/rod.png")
--LoadTexture("../../content/Textures/models/Hero/shield.png")
--LoadTexture("../../content/Textures/models/Hero/shortbow.png")
--LoadTexture("../../content/Textures/models/Hero/shortsword.png")
--LoadTexture("../../content/Textures/models/Hero/slingshot.png")
--LoadTexture("../../content/Textures/models/Hero/staff.png")
--LoadTexture("../../content/Textures/models/Hero/steel_armor.png")
--LoadTexture("../../content/Textures/models/Hero/wand.png")

math.randomseed(1234)

LoadTexture("../../content/Textures/gui/ui_cursor.png")
LoadTexture("../../content/Textures/gui/ui_game.png")
LoadTexture("../../content/Textures/gui/ui_gameMenu.png")

LoadTexture("../../content/Textures/tiles/dirt0.png")
LoadTexture("../../content/Textures/tiles/dirt1.png")
LoadTexture("../../content/Textures/tiles/dirt2.png")

LoadTexture("../../content/Textures/tiles/grass0.png")
LoadTexture("../../content/Textures/tiles/grass1.png")
LoadTexture("../../content/Textures/tiles/grass2.png")
LoadTexture("../../content/Textures/tiles/grass3.png")

LoadTexture("../../content/Textures/tiles/rock.png")
LoadTexture("../../content/Textures/tiles/leaves.png")
LoadTexture("../../content/Textures/tiles/paving.png")
LoadTexture("../../content/Textures/tiles/paving2.png")
LoadTexture("../../content/Textures/tiles/dust.png")
LoadTexture("../../content/Textures/tiles/water.png")
LoadTexture("../../content/Textures/tiles/sand0.png")
LoadTexture("../../content/Textures/font/ExocetLight.png")

LoadTexture("../../content/Textures/doodads/well0.png")
LoadTexture("../../content/Textures/doodads/barell0.png")
LoadTexture("../../content/Textures/doodads/fire0.png")
LoadTexture("../../content/Textures/doodads/cow_corpse0.png")
LoadTexture("../../content/Textures/doodads/tree0.png")
LoadTexture("../../content/Textures/doodads/fountain0.png")

LoadSound("../../content/Music/lakeland.ogg")
InitializeProjectionMatrix(4,10,1000)
InitializeOrthoMatrix(10,1000)
SetCameraPosition(0,0,-1)
AddMusic("lakeland",40,true)
AddModelPaths("../../content/Textures/models/barbarian.mod")
--AddModelPaths("../../content/Textures/models/reaper.mod")
AddModelPaths("../../content/Textures/models/enemy.mod")
--AddModelPaths("../../content/Textures/models/amazon.mod")
--AddModelPaths("../../content/Textures/models/amazon_light.mod")
--AddModelPaths("../../content/Textures/models/paladin.mod")
LoadFont("../../content/Textures/font/ExocetLight.co",432,131)
--PlayMusic("lakeland")